//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administradores
    {
        public int id_administrador { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string empresa { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
