//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_industry_levers
    {
        public Nullable<int> fk_id_value_drivers { get; set; }
        public int id_industry_levers { get; set; }
        public string industry_levers { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cat_value_drivers cat_value_drivers { get; set; }
    }
}
