//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        public Nullable<int> fk_id_cobertura { get; set; }
        public Nullable<int> fk_id_estat_empresa { get; set; }
        public int id_empresa { get; set; }
        public string razon_social { get; set; }
        public string rfc { get; set; }
        public string nombre { get; set; }
        public string web { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string linkedin { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string instagram { get; set; }
        public string descripcion_oferta_valor { get; set; }
        public string sectores_atendidos { get; set; }
        public string principales_clientes { get; set; }
    }
}
