//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuestas
    {
        public int id_encuesta { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_vigencia { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> fk_id_administrador { get; set; }
        public Nullable<double> eversion { get; set; }
        public string nombre { get; set; }
    }
}
