//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estatificacion_empresa
    {
        public Nullable<int> fk_id_tamano { get; set; }
        public Nullable<int> fk_id_nivel_ventas { get; set; }
        public Nullable<int> fk_id_detalle_ventas { get; set; }
        public Nullable<int> fk_id_sector { get; set; }
        public Nullable<int> fk_id_tipo_empresa { get; set; }
        public int id_estat_empresa { get; set; }
    }
}
