//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        public int id_municipio { get; set; }
        public string nombre_municipio { get; set; }
        public Nullable<int> fk_id_estado { get; set; }
    
        public virtual mex_estados mex_estados { get; set; }
    }
}
