//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_vald_ind
    {
        public int id_prod_vald_ind { get; set; }
        public Nullable<int> fk_id_producto { get; set; }
        public string value_driver { get; set; }
        public string industry_levers { get; set; }
    }
}
