//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public Nullable<int> fk_id_posicionamiento { get; set; }
        public Nullable<int> fk_id_marca_nivelp { get; set; }
        public Nullable<int> fk_id_empresa { get; set; }
        public Nullable<int> fk_id_origen { get; set; }
        public Nullable<int> fk_id_tecnologia { get; set; }
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fk_id_value_drivers { get; set; }
        public Nullable<int> fk_industry_levers { get; set; }
        public string caso_exito { get; set; }
        public string referencia { get; set; }
        public string partnership { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> ocupado { get; set; }
        public Nullable<bool> recurso { get; set; }
        public string lenguajes { get; set; }
    }
}
