//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class software_empresa
    {
        public Nullable<int> fk_id_empresa { get; set; }
        public Nullable<int> fk_id_sw { get; set; }
        public int id_sw_emp { get; set; }
    }
}
