//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroalimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public int id_solicitud { get; set; }
        public Nullable<int> fk_id_producto { get; set; }
        public Nullable<int> fk_id_contacto { get; set; }
        public Nullable<int> fk_id_empresa { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<System.DateTime> inicio_periodo { get; set; }
        public Nullable<System.DateTime> fin_periodo { get; set; }
        public string anotaciones { get; set; }
    }
}
